[project]
name = "atem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "cython",
  "dill",
  "empymod",
  "ipykernel",
  "ipywidgets",
  "jupyterlab",
  "libaarhusxyz",
  "matplotlib",
  "nbstripout",
  "numba",
  "pandas",
  "scikit-learn>=1.8.0",
  "simpeg",
]
